-- Digital Banking & Wealth Management Engine schema
CREATE TABLE Customers (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    FullName NVARCHAR(200) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Segment NVARCHAR(50) NOT NULL
);

CREATE TABLE ContactInfo (
    CustomerId UNIQUEIDENTIFIER PRIMARY KEY REFERENCES Customers(Id),
    Email NVARCHAR(200) NOT NULL,
    Phone NVARCHAR(50) NOT NULL,
    Address NVARCHAR(300) NOT NULL
);

CREATE TABLE Branches (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(150) NOT NULL,
    Address NVARCHAR(300) NOT NULL,
    RoutingNumber NVARCHAR(20) NOT NULL
);

CREATE TABLE SavingsAccounts (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL REFERENCES Customers(Id),
    Balance DECIMAL(18,2) NOT NULL,
    InterestRate DECIMAL(9,6) NOT NULL,
    Currency CHAR(3) NOT NULL,
    OpenedOn DATETIME2 NOT NULL
);

CREATE TABLE CurrentAccounts (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL REFERENCES Customers(Id),
    AvailableBalance DECIMAL(18,2) NOT NULL,
    OverdraftLimit DECIMAL(18,2) NOT NULL,
    Currency CHAR(3) NOT NULL
);

CREATE TABLE LoanAccounts (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL REFERENCES Customers(Id),
    Principal DECIMAL(18,2) NOT NULL,
    InterestRate DECIMAL(9,6) NOT NULL,
    TermMonths INT NOT NULL,
    DisbursedOn DATETIME2 NOT NULL
);

CREATE TABLE TransactionLedgers (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    AccountId UNIQUEIDENTIFIER NOT NULL,
    Timestamp DATETIME2 NOT NULL,
    Type NVARCHAR(10) NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Currency CHAR(3) NOT NULL,
    Description NVARCHAR(300) NULL
);

CREATE TABLE PaymentInstructions (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    FromAccountId UNIQUEIDENTIFIER NOT NULL,
    ToAccountId UNIQUEIDENTIFIER NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Currency CHAR(3) NOT NULL,
    ScheduledFor DATETIME2 NOT NULL,
    Status NVARCHAR(30) NOT NULL
);

CREATE TABLE Cards (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    AccountId UNIQUEIDENTIFIER NOT NULL,
    MaskedPan NVARCHAR(25) NOT NULL,
    Expiry DATE NOT NULL,
    ContactlessEnabled BIT NOT NULL
);

CREATE TABLE Beneficiaries (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL REFERENCES Customers(Id),
    Name NVARCHAR(200) NOT NULL,
    Relationship NVARCHAR(100) NOT NULL,
    AllocationPercentage DECIMAL(5,2) NOT NULL
);

CREATE TABLE StockPortfolios (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL REFERENCES Customers(Id),
    Name NVARCHAR(150) NOT NULL,
    BaseCurrency CHAR(3) NOT NULL
);

CREATE TABLE BondPortfolios (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL REFERENCES Customers(Id),
    Name NVARCHAR(150) NOT NULL,
    BaseCurrency CHAR(3) NOT NULL
);

CREATE TABLE MutualFunds (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    ISIN NVARCHAR(20) NOT NULL,
    Nav DECIMAL(18,4) NOT NULL,
    Currency CHAR(3) NOT NULL
);

CREATE TABLE CryptoWallets (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL REFERENCES Customers(Id),
    Address NVARCHAR(200) NOT NULL,
    Network NVARCHAR(50) NOT NULL
);

CREATE TABLE InvestmentAllocations (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    PortfolioId UNIQUEIDENTIFIER NOT NULL,
    AssetClass NVARCHAR(100) NOT NULL,
    TargetPercentage DECIMAL(5,2) NOT NULL
);

CREATE TABLE TradeOrders (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    PortfolioId UNIQUEIDENTIFIER NOT NULL,
    Ticker NVARCHAR(20) NOT NULL,
    Side NVARCHAR(4) NOT NULL,
    Quantity INT NOT NULL,
    LimitPrice DECIMAL(18,4) NOT NULL,
    Status NVARCHAR(20) NOT NULL
);

CREATE TABLE CorporateActions (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Ticker NVARCHAR(20) NOT NULL,
    Type NVARCHAR(50) NOT NULL,
    EffectiveDate DATE NOT NULL,
    Ratio DECIMAL(10,4) NOT NULL
);

CREATE TABLE PerformanceMetrics (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    PortfolioId UNIQUEIDENTIFIER NOT NULL,
    ReturnYtd DECIMAL(9,4) NOT NULL,
    Volatility DECIMAL(9,4) NOT NULL,
    SharpeRatio DECIMAL(9,4) NOT NULL,
    CalculatedOn DATETIME2 NOT NULL
);

CREATE TABLE FeeSchedules (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    PortfolioId UNIQUEIDENTIFIER NOT NULL,
    ManagementFee DECIMAL(9,4) NOT NULL,
    PerformanceFee DECIMAL(9,4) NOT NULL,
    EntryLoad DECIMAL(9,4) NOT NULL
);

CREATE TABLE RebalancingPolicies (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    PortfolioId UNIQUEIDENTIFIER NOT NULL,
    Frequency NVARCHAR(50) NOT NULL,
    DriftThreshold DECIMAL(9,4) NOT NULL,
    LastRebalancedOn DATETIME2 NULL
);

CREATE TABLE RiskAssessments (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL REFERENCES Customers(Id),
    Score INT NOT NULL,
    Category NVARCHAR(50) NOT NULL,
    AssessedOn DATETIME2 NOT NULL
);

CREATE TABLE KYCVerifications (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL REFERENCES Customers(Id),
    Status NVARCHAR(30) NOT NULL,
    VerifiedOn DATETIME2 NULL
);

CREATE TABLE AMLAlerts (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL REFERENCES Customers(Id),
    Severity NVARCHAR(20) NOT NULL,
    RuleId NVARCHAR(50) NOT NULL,
    RaisedOn DATETIME2 NOT NULL,
    Status NVARCHAR(30) NOT NULL
);

CREATE TABLE TransactionMonitoringRules (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(150) NOT NULL,
    Expression NVARCHAR(MAX) NOT NULL,
    Severity NVARCHAR(20) NOT NULL,
    Enabled BIT NOT NULL
);

CREATE TABLE AuditTrail (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    ActorId UNIQUEIDENTIFIER NOT NULL,
    Action NVARCHAR(200) NOT NULL,
    Timestamp DATETIME2 NOT NULL,
    Details NVARCHAR(500) NULL
);

CREATE TABLE TaxDocuments (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL REFERENCES Customers(Id),
    Type NVARCHAR(50) NOT NULL,
    TaxYear INT NOT NULL,
    FilePath NVARCHAR(300) NOT NULL,
    GeneratedOn DATETIME2 NOT NULL
);

CREATE TABLE RegulatoryReports (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    PeriodStart DATE NOT NULL,
    PeriodEnd DATE NOT NULL,
    Status NVARCHAR(30) NOT NULL
);

CREATE TABLE SanctionListEntries (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    FullName NVARCHAR(200) NOT NULL,
    ListName NVARCHAR(100) NOT NULL,
    ListedOn DATE NOT NULL,
    IsActive BIT NOT NULL
);

CREATE TABLE ConsentRecords (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL REFERENCES Customers(Id),
    ConsentType NVARCHAR(100) NOT NULL,
    GrantedOn DATETIME2 NOT NULL,
    RevokedOn DATETIME2 NULL
);

CREATE TABLE DataRetentionPolicies (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    DataCategory NVARCHAR(100) NOT NULL,
    RetentionMonths INT NOT NULL,
    AutoPurgeEnabled BIT NOT NULL
);
